name=MotorMixers
version=0.0.7
author=Martin Budden
maintainer=Martin Budden
sentence=Motor mixers
paragraph=
category=Device Control
url=https://github.com/martinbudden/Library-MotorMixers.git
architectures=*
includes=Debug.h, DshotCodec.h, DynamicIdleController.h, ESC_DShot.h, ESC_DShotBitbang.h, EscDshotBitbangIRQ.h, Mixers.h, MotorMixerBase.h, MotorMixerOctoBase.h, MotorMixerQuadBase.h, MotorMixerQuadXDshot.h, MotorMixerQuadXDshotBitbang.h, MotorMixerQuadXPwm.h, RPM_Filters.h
