name=MotorMixers
version=0.0.7
author=Martin Budden
maintainer=Martin Budden
sentence=Motor mixers
paragraph=
category=Device Control
url=https://github.com/martinbudden/Library-MotorMixers.git
architectures=*
includes=dshot_codec.h, dynamic_idle_controller.h, esc_dshot.h, esc_dshot_bitbang.h, esc_dshot_bitbang_irq.h, mixers.h, motor_mixer_base.h, motor_mixer_octo_base.h, motor_mixer_quad_base.h, motor_mixer_quadx_dshot.h, motor_mixer_quadx_dshot_bitbang.h, motor_mixer_quadx_pwm.h, rpm_filters.h
